spring:
  application:
    name: board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/post?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234



